# Generated by Django 3.1.14 on 2022-05-27 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220527_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='stop_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
