# Generated by Django 3.1.14 on 2022-05-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220527_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
