# Generated by Django 3.1.14 on 2022-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220527_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='stop_time',
            field=models.TimeField(blank=True),
        ),
    ]
