# Generated by Django 3.1.14 on 2022-05-27 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20220527_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
